version = 0.1

[default.deploy.parameters]
stack_name = "lpr-layer-proxy"
resolve_s3 = true
s3_prefix = "lpr-layer-proxy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
